//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fa_app_version> fa_app_version { get; set; }
        public virtual DbSet<fa_bulletin> fa_bulletin { get; set; }
        public virtual DbSet<fa_bulletin_log> fa_bulletin_log { get; set; }
        public virtual DbSet<fa_bulletin_review> fa_bulletin_review { get; set; }
        public virtual DbSet<fa_bulletin_type> fa_bulletin_type { get; set; }
        public virtual DbSet<fa_config> fa_config { get; set; }
        public virtual DbSet<fa_db_server> fa_db_server { get; set; }
        public virtual DbSet<fa_db_server_type> fa_db_server_type { get; set; }
        public virtual DbSet<fa_district> fa_district { get; set; }
        public virtual DbSet<fa_dynasty> fa_dynasty { get; set; }
        public virtual DbSet<fa_elder> fa_elder { get; set; }
        public virtual DbSet<fa_export_log> fa_export_log { get; set; }
        public virtual DbSet<fa_family> fa_family { get; set; }
        public virtual DbSet<fa_files> fa_files { get; set; }
        public virtual DbSet<fa_flow> fa_flow { get; set; }
        public virtual DbSet<fa_flow_flownode> fa_flow_flownode { get; set; }
        public virtual DbSet<fa_flow_flownode_flow> fa_flow_flownode_flow { get; set; }
        public virtual DbSet<fa_function> fa_function { get; set; }
        public virtual DbSet<fa_log> fa_log { get; set; }
        public virtual DbSet<fa_login> fa_login { get; set; }
        public virtual DbSet<fa_login_history> fa_login_history { get; set; }
        public virtual DbSet<fa_message> fa_message { get; set; }
        public virtual DbSet<fa_message_type> fa_message_type { get; set; }
        public virtual DbSet<fa_module> fa_module { get; set; }
        public virtual DbSet<fa_oauth> fa_oauth { get; set; }
        public virtual DbSet<fa_query> fa_query { get; set; }
        public virtual DbSet<fa_role> fa_role { get; set; }
        public virtual DbSet<fa_role_config> fa_role_config { get; set; }
        public virtual DbSet<fa_role_query_authority> fa_role_query_authority { get; set; }
        public virtual DbSet<fa_script> fa_script { get; set; }
        public virtual DbSet<fa_script_group_list> fa_script_group_list { get; set; }
        public virtual DbSet<fa_script_task> fa_script_task { get; set; }
        public virtual DbSet<fa_script_task_log> fa_script_task_log { get; set; }
        public virtual DbSet<fa_sms_send> fa_sms_send { get; set; }
        public virtual DbSet<fa_task> fa_task { get; set; }
        public virtual DbSet<fa_task_flow> fa_task_flow { get; set; }
        public virtual DbSet<fa_task_flow_handle> fa_task_flow_handle { get; set; }
        public virtual DbSet<fa_task_flow_handle_user> fa_task_flow_handle_user { get; set; }
        public virtual DbSet<fa_user> fa_user { get; set; }
        public virtual DbSet<fa_user_event> fa_user_event { get; set; }
        public virtual DbSet<fa_user_info> fa_user_info { get; set; }
        public virtual DbSet<fa_user_message> fa_user_message { get; set; }
        public virtual DbSet<fa_updata_log> fa_updata_log { get; set; }
    }
}
