//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_bulletin_review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fa_bulletin_review()
        {
            this.fa_bulletin_review1 = new HashSet<fa_bulletin_review>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public int BULLETIN_ID { get; set; }
        public string NAME { get; set; }
        public string CONTENT { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime ADD_TIME { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUS_TIME { get; set; }
    
        public virtual fa_bulletin fa_bulletin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_bulletin_review> fa_bulletin_review1 { get; set; }
        public virtual fa_bulletin_review fa_bulletin_review2 { get; set; }
    }
}
