//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_bulletin_log
    {
        public int ID { get; set; }
        public int BULLETIN_ID { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime LOOK_TIME { get; set; }
    
        public virtual fa_bulletin fa_bulletin { get; set; }
    }
}
