//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_bulletin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fa_bulletin()
        {
            this.fa_bulletin_log = new HashSet<fa_bulletin_log>();
            this.fa_bulletin_review = new HashSet<fa_bulletin_review>();
            this.fa_files = new HashSet<fa_files>();
            this.fa_role = new HashSet<fa_role>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string PIC { get; set; }
        public string TYPE_CODE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string PUBLISHER { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public decimal IS_SHOW { get; set; }
        public decimal IS_IMPORT { get; set; }
        public decimal IS_URGENT { get; set; }
        public decimal AUTO_PEN { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
        public string REGION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_bulletin_log> fa_bulletin_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_bulletin_review> fa_bulletin_review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_files> fa_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_role> fa_role { get; set; }
    }
}
