//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_flow_flownode_flow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fa_flow_flownode_flow()
        {
            this.fa_role = new HashSet<fa_role>();
        }
    
        public int ID { get; set; }
        public int FLOW_ID { get; set; }
        public int FROM_FLOWNODE_ID { get; set; }
        public int TO_FLOWNODE_ID { get; set; }
        public decimal HANDLE { get; set; }
        public decimal ASSIGNER { get; set; }
        public string STATUS { get; set; }
        public string REMARK { get; set; }
        public int EXPIRE_HOUR { get; set; }
    
        public virtual fa_flow fa_flow { get; set; }
        public virtual fa_flow_flownode fa_flow_flownode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_role> fa_role { get; set; }
    }
}
