//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_script_task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fa_script_task()
        {
            this.fa_script_task_log = new HashSet<fa_script_task_log>();
        }
    
        public int ID { get; set; }
        public int SCRIPT_ID { get; set; }
        public string BODY_TEXT { get; set; }
        public string BODY_HASH { get; set; }
        public string RUN_STATE { get; set; }
        public string RUN_WHEN { get; set; }
        public string RUN_ARGS { get; set; }
        public string RUN_DATA { get; set; }
        public Nullable<decimal> LOG_TYPE { get; set; }
        public string DSL_TYPE { get; set; }
        public string RETURN_CODE { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<System.DateTime> DISABLE_DATE { get; set; }
        public string DISABLE_REASON { get; set; }
        public string SERVICE_FLAG { get; set; }
        public string REGION { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
    
        public virtual fa_script fa_script { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_script_task_log> fa_script_task_log { get; set; }
    }
}
