//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_script_group_list
    {
        public int SCRIPT_ID { get; set; }
        public int GROUP_ID { get; set; }
        public int ORDER_INDEX { get; set; }
    
        public virtual fa_script fa_script { get; set; }
    }
}
