//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_sms_send
    {
        public string GUID { get; set; }
        public Nullable<int> MESSAGE_ID { get; set; }
        public string PHONE_NO { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public Nullable<System.DateTime> SEND_TIME { get; set; }
        public string CONTENT { get; set; }
        public string STAUTS { get; set; }
        public int TRY_NUM { get; set; }
    }
}
