//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_task_flow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fa_task_flow()
        {
            this.fa_task_flow1 = new HashSet<fa_task_flow>();
            this.fa_task_flow_handle = new HashSet<fa_task_flow_handle>();
            this.fa_task_flow_handle_user = new HashSet<fa_task_flow_handle_user>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public int TASK_ID { get; set; }
        public Nullable<int> LEVEL_ID { get; set; }
        public Nullable<int> FLOWNODE_ID { get; set; }
        public Nullable<int> EQUAL_ID { get; set; }
        public int IS_HANDLE { get; set; }
        public string NAME { get; set; }
        public string HANDLE_URL { get; set; }
        public string SHOW_URL { get; set; }
        public Nullable<System.DateTime> EXPIRE_TIME { get; set; }
        public System.DateTime START_TIME { get; set; }
        public string DEAL_STATUS { get; set; }
        public string ROLE_ID_STR { get; set; }
        public Nullable<int> HANDLE_USER_ID { get; set; }
        public Nullable<System.DateTime> DEAL_TIME { get; set; }
        public Nullable<System.DateTime> ACCEPT_TIME { get; set; }
    
        public virtual fa_task fa_task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_task_flow> fa_task_flow1 { get; set; }
        public virtual fa_task_flow fa_task_flow2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_task_flow_handle> fa_task_flow_handle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_task_flow_handle_user> fa_task_flow_handle_user { get; set; }
    }
}
