//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_user_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fa_user_info()
        {
            this.fa_user_event = new HashSet<fa_user_event>();
            this.fa_user_info1 = new HashSet<fa_user_info>();
            this.fa_user1 = new HashSet<fa_user>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LEVEL_ID { get; set; }
        public Nullable<int> FAMILY_ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public string LEVEL_NAME { get; set; }
        public Nullable<int> FATHER_ID { get; set; }
        public Nullable<int> MOTHER_ID { get; set; }
        public Nullable<System.DateTime> BIRTHDAY_TIME { get; set; }
        public string BIRTHDAY_PLACE { get; set; }
        public Nullable<decimal> IS_LIVE { get; set; }
        public Nullable<System.DateTime> DIED_TIME { get; set; }
        public string DIED_PLACE { get; set; }
        public string REMARK { get; set; }
        public string SEX { get; set; }
        public string YEARS_TYPE { get; set; }
        public Nullable<int> CONSORT_ID { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_USER_NAME { get; set; }
        public int CREATE_USER_ID { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
        public string UPDATE_USER_NAME { get; set; }
        public int UPDATE_USER_ID { get; set; }
    
        public virtual fa_elder fa_elder { get; set; }
        public virtual fa_family fa_family { get; set; }
        public virtual fa_user fa_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_user_event> fa_user_event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_user_info> fa_user_info1 { get; set; }
        public virtual fa_user_info fa_user_info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_user> fa_user1 { get; set; }
    }
}
