//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_updata_log
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string CREATE_USER_NAME { get; set; }
        public Nullable<int> CREATE_USER_ID { get; set; }
        public string OLD_CONTENT { get; set; }
        public string NEW_CONTENT { get; set; }
        public string TABLE_NAME { get; set; }
    }
}
