//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_user_message
    {
        public int MESSAGE_ID { get; set; }
        public int USER_ID { get; set; }
        public string PHONE_NO { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUS_TIME { get; set; }
        public string REPLY { get; set; }
        public string PUSH_TYPE { get; set; }
    
        public virtual fa_message fa_message { get; set; }
    }
}
