//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_user_event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fa_user_event()
        {
            this.fa_files = new HashSet<fa_files>();
        }
    
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> HAPPEN_TIME { get; set; }
        public string CONTENT { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual fa_user_info fa_user_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_files> fa_files { get; set; }
    }
}
